name: Autograding Tests

on:
  pull_request:
    branches: [ main, develop ]
  push: 
    branches: [ main, develop ]

jobs:
  build:
    runs-on: [self-hosted, linux, data-structures]

    steps:
    - uses: actions/checkout@v4

    - name: Compile and Test All Activities
      run: |
        cd .github/
        chmod +x scripts/evaluate.sh
        ./scripts/evaluate.sh

    - name: Upload Results as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: results.md